var express = require('express');
var router = express.Router();
const env = require('../config/env/environment');
var context = env.context || "/cms";

//router.use(context, require('./login'));
//router.use(context, require('./register'));
router.use(context, require('./appLaunch'));
router.use(context, require('./introScreen'));
router.use(context, require('./newsAndPromo'));
router.use(context, require('./fileUploader'));
router.use(context, require('./multifileUploader'));
router.use(context, require('./comments'));
router.use(context, require('./appsCenter'));
router.use(context, require('./homeScreen'));
router.use(context, require('./appCategories'));
router.use(context, require('./creditProducts'));
router.use(context, require('./creditSimulation'));
router.use(context, require('./auction'));
router.use(context, require('./user'));
router.use(context, require('./productCatalogue'));
router.use(context, require('./customerGroup'));
router.use(context, require('./notification'));
router.use(context, require('./pointHistory'));
router.use(context, require('./pointManagement'));
router.use(context, require('./bankInfo'));
router.use(context, require('./customerRedemption'));
router.use(context, require('./creditApplication'));
router.use(context, require('./surveyQuestioner'));
router.use(context, require('./manageRating'));
router.use(context, require('./otp'));
router.use(context, require('./customerProfile'));
router.use(context, require('./viewRating'));
router.use(context, require('./admin'));
router.use(context, require('./roles'));
router.use(context, require('./complaint'));
router.use(context, require('./stnk'));
router.use(context, require('./bpkb'));
router.use(context, require('./claimInsurance'));
router.use(context, require('./sinatra'));
router.use(context, require('./changeOwnership'));
router.use(context, require('./appSource'));
router.use(context, require('./activity'));
router.use(context, require('./dropdownList'));
router.use(context, require('./fgc'));
router.use(context, require('./help'));
router.use(context, require('./contracts'));
router.use(context, require('./documents'));
router.use(context, require('./fgcMember'));
router.use(context, require('./locations'));
router.use(context, require('./appNotificationSettings'));
router.use(context, require('./stnkVerification'));
router.use(context, require('./scheduler'));
router.use(context, require('./dashboard'));
router.use(context, require('./reports'));
router.use(context, require('./astraPay'));
router.use(context, require('./fmcBookingReservation'));
module.exports = router;